In [23]:
import xlrd
import numpy as np
import pandas as pd

In [97]:
#读取计提标准及揽投量.xls文件
sheets = xlrd.open_workbook("江门补充资料/计提标准及揽投量.xls", 'r')
sheet = sheets.sheets()[0]
nrows = sheet.nrows
infos = []
for row in range(2, nrows):
    info = [sheet.row(row)[4].value, sheet.row(row)[6].value, sheet.row(row)[7].value]
    infos.append(info)

In [58]:
#读取揽投机构信息，机构名称有缩写有完整，有可能加个（支部），所以改用编号
data_lanshou = pd.read_csv('江门揽收数据.csv', encoding='gb18030', usecols=[6])
data_lanshou = np.array(data_lanshou)
data_toudi21 = pd.read_csv('toudi_21.csv', encoding='gb18030', usecols=[4])
data_toudi21 = np.array(data_toudi21)
data_toudi22 = pd.read_csv('toudi_22.csv', encoding='gb18030', usecols=[4])
data_toudi22 = np.array(data_toudi22)
data_toudi206 = pd.read_csv('toudi_206.csv', encoding='gb18030', usecols=[4])
data_toudi206 = np.array(data_toudi206)

In [70]:
#统计各个机构的揽投数量
checks = []

for info in infos:
    lanshou_counts = ((data_lanshou == info[0]).sum())
    toudi_counts = ((data_toudi21 == info[0]).sum() + (data_toudi22 == info[0]).sum() + (data_toudi206 == info[0]).sum())

    lanshou_check = 1 if lanshou_counts == info[1] else 0
    toudi_check = 1 if lanshou_counts == info[2] else 0
    
    checks.append([int(info[0]), lanshou_counts, toudi_counts, lanshou_check, toudi_check])

In [123]:
checks = np.array(checks)
print(checks)
with open('check.csv', 'w', encoding='gb18030', newline='') as f:
    writer = csv.writer(f)
    writer.writerow(['机构代码', "揽收量", "投递量", "揽收量一致否", "投递量一致否"])
    writer.writerows(checks)

[[52907504    16164    68384        0        0]
 [52908006    18804    75854        0        0]
 [52908504     3001    47779        0        0]
 [52909506     3819    67829        0        0]
 [52900009    16022    72390        0        0]
 [52900010     4795    56804        0        0]
 [52900057     3553    43925        0        0]
 [52903014     6558    37717        0        0]
 [52909003     7821    73803        0        0]
 [52910017     8816   153290        0        0]
 [52910019    14742    62452        0        0]
 [52914202      514    11072        0        0]
 [52910032      280    11727        0        0]
 [52910033      759    13763        0        0]
 [52910035     2188    14071        0        0]
 [52910036      290    15349        0        0]
 [52910037      157     8909        0        0]
 [52910038     1585    29891        0        0]
 [52910039      560    17503        0        0]
 [52910046     5868    18747        0        0]
 [52915302     1561    20760        0   

In [74]:
#二，三列分别为揽收，投递总计数
print(np.sum(checks, axis=0, keepdims=True))

[[-113564485     282403    1894983          0          0]]


In [118]:
data_lanshou_ = pd.Series(data_lanshou.flatten()).value_counts()
print(data_lanshou_)

52908503    668417
52900004    269826
52936900    144670
52904006     91328
52900007     84145
             ...  
52914901         4
52908502         3
52900061         3
52925801         2
52943101         1
Length: 214, dtype: int64
